### ISSUE TITLE
Travis Bot

### ISSUE THREAD

**Issue by VinceBackpack** [yevseytsev/SenecaBlackboardExtension#123]
The files for ESLint and Travis is already in the code but to activate Travis bot the owner(@yevseytsev) of this repo has to connect this repo to [Travis](https://travis-ci.org/)

**Comment by yevseytsev** [comment]
@VinceBackpack Done, not sure whether I did everything right. Let me know if something needs to be changed/fixed

**Comment by VinceBackpack** [comment]
@yevseytsev Works like a charm!
