### ISSUE TITLE
Add Reset/Forgot your password link to this sign in page (https://my.senecacollege.ca/webapps/login/?action=relogin)

### ISSUE THREAD

**Issue by susantruong** [yevseytsev/SenecaBlackboardExtension#13]
I wasn't able to reset my password when I was on this [sign in](https://my.senecacollege.ca/webapps/login/?action=relogin) page. I want to add this function.

**Comment by ooHAoo** [comment]
I would like to work on this if you won't be working on it :)

**Comment by susantruong** [comment]
@ooHAOO Sorry, I am working on it.

**Comment by yevseytsev** [comment]
@susantruong go for it!
