### ISSUE TITLE
Could not load manifest 

### ISSUE THREAD

**Issue by VinceBackpack** [yevseytsev/SenecaBlackboardExtension#27]
Could not load manifest on google chrome.
![image](https://user-images.githubusercontent.com/18684033/48236476-61c69480-e390-11e8-850c-5d566ea5cb77.png)

**Comment by VinceBackpack** [comment]
I'll work on it. I have an idea of how to fix it.

**Comment by VinceBackpack** [comment]
#28  Fixed

**Comment by yevseytsev** [comment]
@VinceBackpack thanks!
