### ISSUE TITLE
Add the email link to the default page of https://my.senecacollege.ca

### ISSUE THREAD

**Issue by Peng-Qu** [yevseytsev/SenecaBlackboardExtension#3]
There is no email link in the default page of senecacollege website. Each time I need to login to my email, I have to login in to the blackboard first, and then click the email link to the email.
This extension is to add the email link to the default page.

**Comment by Peng-Qu** [comment]
Reference: https://github.com/sindresorhus/refined-twitter or https://github.com/sindresorhus/refined-github

**Comment by yevseytsev** [comment]
@Peng-Qu go for it!
