### ISSUE TITLE
npm install command specified in the Readme Workflow section fails

### ISSUE THREAD

**Issue by dnguneratne** [yevseytsev/SenecaBlackboardExtension#43]
The [Workflow](https://github.com/dnguneratne/SenecaBlackboardExtension#workflow) section of the Readme file instructs to run `npm install` after cloning. However, there is no npm modules in this repo. Is it supposed to be that way or did the `.package.json` file not get added?

**Comment by yevseytsev** [comment]
@dnguneratne you are right, do you want to fix it?

**Comment by yevseytsev** [comment]
fixed
