### ISSUE TITLE
Add extension settings page

### ISSUE THREAD

**Issue by dnguneratne** [yevseytsev/SenecaBlackboardExtension#44]
It would be nice to have a settings page for the extension that allows the user to choose which parts of Seneca Blackboard they want to toggle.

**Comment by humphd** [comment]
Agree.  This is one of the reasons I suggested this project begin by forking something like [Refined Twitter](https://github.com/sindresorhus/refined-twitter) which already has this implemented.

**Comment by Casva** [comment]
I'd like to try to tackle this one!
