### ISSUE TITLE
Adding a button to change the font of texts

### ISSUE THREAD

**Issue by YuechengWu** [yevseytsev/SenecaBlackboardExtension#46]
Hi, I would like to add a button to change the size, style of the texts on the page, maybe more. Thanks!

**Comment by yevseytsev** [comment]
@YuechengWu this feature requires fixes, I have commented the code right now

**Comment by YuechengWu** [comment]
@yevseytsev Hi, what fixes are required? Did you commented on the code or did you commented out the code?

**Comment by yevseytsev** [comment]
@YuechengWu buttons are just not working, I commented a code in the files, so you can't fix it when you have time :)

**Comment by YuechengWu** [comment]
@yevseytsev Another friend actually has told me the same issue with buttons not working, but they are working on my laptop. I will look into this.
