### ISSUE TITLE
Join the Slack Channel!

### ISSUE THREAD

**Issue by Casva** [yevseytsev/SenecaBlackboardExtension#5]
Hey everyone!
It'd probably be a good idea to create a Slack workspace for any kind of discussion that we may need.

I've created one already for everyone to join, just click [here](https://join.slack.com/t/seneca-web-extension/shared_invite/enQtNDczNTEwMzE5NzgzLTA1NTk0YzIxMzM4YTcwYTQ5ZDNjMjZiMDRhMGUxZGIyODQ3OWVjZGIwZWJkNGFmYTk0ZGMzNDE2NTRlMmM2ZTM) 😀

**Comment by yevseytsev** [comment]
@Casva thank you! This was added to readme file
