### ISSUE TITLE
Add link of Seneca Important Dates, Seneca Library and Seneca Faculty and Staff and change font size

### ISSUE THREAD

**Issue by charBap** [yevseytsev/SenecaBlackboardExtension#69]
Seneca Important Dates: http://www.senecacollege.ca/registrar/dates/
Seneca Libraries: http://library.senecacollege.ca/
Seneca Faculty and Staff: https://inside.senecacollege.ca/its/support/myseneca/faculty/course_management/introduction.html

**Comment by yuzhouChen** [comment]
I would like work on this

**Comment by yevseytsev** [comment]
@yuzhouChen go for it

**Comment by Janice0218** [comment]
can i take it ?

**Comment by yuzhouChen** [comment]
@Janice0218 Sorry, I'm still working on this one

**Comment by Janice0218** [comment]
ok

**Comment by yuzhouChen** [comment]
This issue has already been fixed by somebody
