### ISSUE TITLE
Remove useless parts of the website

### ISSUE THREAD

**Issue by yevseytsev** [yevseytsev/SenecaBlackboardExtension#7]
Seneca News
Seneca Spotlight
Did You Know?
Quickly
Useless announcements (Full-Time Student News, Student News)

**Comment by deepanjali19** [comment]
I am working on it @yevseytsev !!

**Comment by deepanjali19** [comment]
@yevseytsev created a PR 🥇

**Comment by yuzhouChen** [comment]
I would like to remove the Seneca News part

**Comment by Janice0218** [comment]
I would like to remove Seneca Spotlight

**Comment by itchylol742** [comment]
I can remove Qwickly
