### ISSUE TITLE
Organize modules that left after removing useless parts

### ISSUE THREAD

**Issue by yevseytsev** [yevseytsev/SenecaBlackboardExtension#8]

**Comment by yevseytsev** [comment]
@VictorKubrak of course, go for it!

**Comment by ooHAoo** [comment]
> I want to do this. As well I would like to style the modules

Hey! Are you working on the part when the user is signed in or before they are signed in?

**Comment by yevseytsev** [comment]
@ooHAoo @VictorKubrak Victor finished it, feel free to open new issue if you want to add more design
